src/genboy/Festival/Area.php
src/genboy/Festival/Main.php

Commands assigned to event types enter/leave/center area

Command events

---

.editorconfig
src/genboy/Festival/Area.php
src/genboy/Festival/Main.php

The code was quite hard to review due to very mixed&wrong indenting. (Space/Tabs are evil!)
Also, I did the switch layout this way:
```php
switch(){
case "blah":
content;
break;
default:
content;
break;
}
```
If you like to have the break; still aligned with the content, I can do that too.
Also, you should consider unifying your if style, because you have mixed
```php
if(expression){
}
```
with
```php
if (expression) {
}
```
and
```php
if( expression ){
}
```
but I’ll leave that up to you.

Fixed indenting, now tabs everywhere

---

.poggit.yml

workflow starts at master, develops in development [poggit dev] and ends in stable release branch

Last intake reorder branches

---

.poggit.yml
README.md
plugin.yml
resources/config.yml
src/genboy/Festival/Area.php
src/genboy/Festival/Main.php

Version bump for now, more info in [issue](https://github.com/genboy/Festival/issues/27)

v1.0.4-12 dev

---

README.md
plugin.yml
resources/config.yml
src/genboy/Festival/Main.php

Added  effect flag, 
and autowhitelist(off) option
+ flag list

update dev 1.0.5-12

---

src/genboy/Festival/Main.php

Now '@p' can be used in area event commands (to use commands that need the playername :)

Playername (@p) command filter!

---

src/genboy/Festival/Main.php

Just did a quick fix to the @p variable
Since it didnt work i propose the {player} variable

Updated @p to {player}

---

README.md
plugin.yml
resources/config.yml
src/genboy/Festival/Area.php
src/genboy/Festival/Main.php

PVP free zones now available by setting the area pvp-flag!
Flight flag is a bit experimental, seems a bit laggy and slow, looking for a better way to fix no-flight detection.

PVP Flag & Flight

---

resources/config.yml
src/genboy/Festival/Main.php

Improvements to Effects, Flight and PVP flags

Fixes & improvements

---

plugin.yml
resources/config.yml
src/genboy/Festival/Main.php

last dev v1.0.6-13

---

plugin.yml

To far ahead in api version fixed

Api Version OK

---

README.md
plugin.yml
resources/config.yml
src/genboy/Festival/Main.php

Api 3.0.0 - 4.0.0 ( 5.0.0 )

---

plugin.yml
src/genboy/Festival/Main.php

event player canDamage false extinguish fire

extinguish fire

---

README.md
plugin.yml
resources/config.yml
src/genboy/Festival/Main.php

v1.0.7
dev tested with 
PocketMine-MP version 1.7dev-1001 "[REDACTED]" (API 3.0.0-ALPHA12),
PocketMine-MP version 3.1.0, 
PocketMine-MP version 4.0.0+dev.1334.

Release v1.0.7

---

plugin.yml
src/genboy/Festival/Main.php

For api 3.0.0 .. 
Request if 4.0.0 -dev is needed

Msg rules dbug flight & warnings

---

README.md
plugin.yml
resources/config.yml
src/genboy/Festival/Main.php

The code can be rewritten to loose many function loops, this will be a major change to all flag functions in the following updates.

Dev update 1.0.7.2

---

plugin.yml
resources/config.yml
src/genboy/Festival/Main.php

Fix flags default (rule order) and FallDamage rename + config flag info

Fixes & naming

---

README.md
plugin.yml
resources/config.yml
src/genboy/Festival/Main.php

- Prevent mob spawning (and spawners/eggs) in area's 
- mobs flag - no spawning
- animals flag  - no spawning
- protect farmland creation (edit flag)
- protect item in frame use (edit flag)

1,0,7,5-dev

---

README.md
src/genboy/Festival/Main.php

- fire flag extinguishing players and blocks (onblockupdate) 
- flag info update

fire flag extinguishing players and blocks (onblockupdate) +info update

---

plugin.yml
src/genboy/Festival/Main.php

Fix Typos on translate strings (no PVP message)

Translate fixed & new codesign

---

resources/en.json
src/genboy/Festival/Main.php

Fire flag onBlockUpdate 
> get position from block->level 
> replaced setBlockIdAt with setBlock

fire replace block->level setblock air

---

resources/nl.json
src/genboy/Festival/Main.php

Fix inArea Player availabillity after [error report](https://github.com/genboy/Festival/issues/113)  
including player damage cause check order (pvp/god/dodamage)
+ nl translation

Fix inArea Player PVP

---

README.md
src/genboy/Festival/Main.php

Added array variable isset playername befor using inArea

Player inArea checks

---

src/genboy/Festival/Main.php

can entity MysterySkull spawn

---

README.md
plugin.yml
resources/config.yml
resources/en.json
resources/nl.json
src/genboy/Festival/Main.php

- gmc flying allowed by default
- fix inArea Player availabillity
- fix player damage cause check

Update to version 1.0.9

---

resources/config.yml
resources/es.json

Gracias por sus traducciones @bptube!
Los revisaré desde from this branch

Merge Spanish translation thanks bptube!

---

src/genboy/Festival/Festival.php

Preventing server crash on entity remove at start with flagForDespawn

debug entity isValid

---

.gitignore
README.md
resources/config.yml
src/genboy/Festival/Festival.php
src/genboy/Festival/FormUI.php
src/genboy/Festival/Helper.php
src/genboy/Festival/Level.php

For each level select to use the level flag restrictions ( vs config defaults )

Level control option

---

README.md
src/genboy/Festival/Festival.php
src/genboy/Festival/FormUI.php
src/genboy/Festival/Helper.php

- fall flag fix
- level config debug (turn on/off level flag usage)
- edit flag painting bug fixed half no placing (still breaking, in progress)
- whitelist bug fix
- slappers allowed by mob/animal flag
+ compass options testing

Bug fixes 0.1

---

src/genboy/Festival/Festival.php
src/genboy/Festival/Helper.php

This development update has minor fixes to actual problems and awaits the development of some open issues on Flight flag, falldamage flag and plugin combination usage.

Dev update smallfixes

---

resources/en.json
resources/es.json
resources/nl.json
resources/pl.json
src/genboy/Festival/Festival.php
src/genboy/Festival/FormUI.php

Fix Falldamage & compass translations 
+ minor details in text and code

Fix Falldamage & compass translations

---

COPYRIGHT
resources/config.yml
src/genboy/Festival/Festival.php
src/genboy/Festival/FormUI.php
src/genboy/Festival/Helper.php

ru.json
`{
"language-name": "Russian",
"language-selected": "Выбран язык Русский.",
"enabled-console-msg": "Фестиваль теперь включен, выбран язык русский (переключить язык командой /fe lang <en/nl/es/pl/ru>).",
"cmd-ingameonly-msg": "Команда фестиваля только для использования в игре.",
"cmd-unknown-msg": "Неизвестная команда фестиваля",
"cmd-noperms-msg": "Вы не можете использовать эту команду фестиваля",
"cmd-noperms-subcommand": "У вас нет разрешения на использование этой подкоманды.",
"pos-select-active": "Вы уже выбираете позицию!",
"select-both-pos-first":"Пожалуйста, выберите 2 координаты, поставив или разбив 2 позиции в первую очередь.",
"pos1": "позиция 1",
"pos2": "позиция 2",
"make-pos1": "Пожалуйста, поставьте или разбейте первую позицию.",
"make-pos2": "Пожалуйста, установите …

language russian

---

src/neitanod/ForceUTF8/Encoding.php

fix namespace encoding.php

---

README.md
src/genboy/Festival/Festival.php

- Russian (ru) translations
- French (fr) translations
- Add right-click position selection in air
- Barrier op msg fix
- ForceUTF8 update fix PHP 7.4
- Debugged global eventhandling
- Area selection with Midair

Towards v2.1.2

---

src/genboy/Festival/Festival.php

Thank you Benda, i go research and test this on my local server

Pull for research damage problem

---

plugin.yml
src/genboy/Festival/Area.php
src/genboy/Festival/Festival.php
src/genboy/Festival/FormUI.php
src/genboy/Festival/Helper.php

Fix losing the compass
https://poggit.pmmp.io/ci/genboy/Festival/Festival/dev:122

Development Fix losing the compass

---

plugin.yml
src/genboy/Festival/Area.php
src/genboy/Festival/Festival.php
src/genboy/Festival/FormUI.php
src/genboy/Festival/Helper.php

Pulled fro update to setup flag translation/renaming

Update from Development
